INSERT INTO genre (genre_name) VALUES ('Multi-player');
INSERT INTO genre (genre_name) VALUES ('Single-player');
INSERT INTO genre (genre_name) VALUES ('First-person shooter');
INSERT INTO genre (genre_name) VALUES ('Couch Co-op');
INSERT INTO genre (genre_name) VALUES ('Virtual Reality');
INSERT INTO genre (genre_name) VALUES ('Puzzle');
INSERT INTO genre (genre_name) VALUES ('Simulation');
INSERT INTO genre (genre_name) VALUES ('Strategy');
INSERT INTO genre (genre_name) VALUES ('Open world');
INSERT INTO genre (genre_name) VALUES ('Sports');
INSERT INTO genre (genre_name) VALUES ('Role-playing');
INSERT INTO genre (genre_name) VALUES ('Action');
INSERT INTO genre (genre_name) VALUES ('MMO');
INSERT INTO genre (genre_name) VALUES ('Online Only');
INSERT INTO genre (genre_name) VALUES ('Adventure');

INSERT INTO console (console_name) VALUES ('Playstation 1');
INSERT INTO console (console_name) VALUES ('Playstation 2');
INSERT INTO console (console_name) VALUES ('Playstation 3');
INSERT INTO console (console_name) VALUES ('Playstation 4');
INSERT INTO console (console_name) VALUES ('Playstation 5');
INSERT INTO console (console_name) VALUES ('XBOX original');
INSERT INTO console (console_name) VALUES ('XBOX 360');
INSERT INTO console (console_name) VALUES ('XBOX ONE');
INSERT INTO console (console_name) VALUES ('XBOX Series X');
INSERT INTO console (console_name) VALUES ('XBOX Series S');
INSERT INTO console (console_name) VALUES ('PC');
INSERT INTO console (console_name) VALUES ('SteamDeck');
INSERT INTO console (console_name) VALUES ('Nintendo Switch');
INSERT INTO console (console_name) VALUES ('Nintendo Wii');
INSERT INTO console (console_name) VALUES ('Nintendo WiiU');
INSERT INTO console (console_name) VALUES ('Nintendo GameCube');
INSERT INTO console (console_name) VALUES ('Nintendo 64');
INSERT INTO console (console_name) VALUES ('Nintendo SuperNintendo');
INSERT INTO console (console_name) VALUES ('Nintendo Original');
INSERT INTO console (console_name) VALUES ('Atari');
INSERT INTO console (console_name) VALUES ('Other');